kind: pipeline
type: docker
name: SE-350

steps:
  - name: install
    image: node
    commands:
      # - yarn config set cache-folder /drone/src/yarn_cache
      - yarn install --pure-lockfile
    when:
      branch:
        - master

  - name: build
    image: node
    commands:
      - unset CI
      - yarn build
    when:
      branch:
        - master

  - name: docker
    image: plugins/docker
    settings:
      insecure: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: chuyuxuan/se-350-interview-platform
      tags:
        - v1.0.0
    when:
      branch:
        - master
# volumes:
#   - name: cache
#     host:
#       path: /var/tmp/cache
