kind: pipeline
type: docker
name: SE-350

steps:
  - name: install
    image: node
    commands:
      # - yarn config set cache-folder /drone/src/yarn_cache
      - yarn install --pure-lockfile
    when:
      branch:
        - master

  - name: build
    image: node
    commands:
      - unset CI
      - yarn build
    when:
      branch:
        - master

  # - name: docker
  #   image: plugins/docker
  #   settings:
  #     insecure: true
  #     volumes:
  #       - name: docker_sock
  #         path: /var/run/docker.sock
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #     repo: chuyuxuan/se-350-interview-platform
  #     tags:
  #       - v1.0.0
  #   when:
  #     branch:
  #       - master
    - name: docker
      image: docker:latest
      volumes:
        - name: docker_sock
          path: /var/run/docker.sock
      commands:
        - docker build --no-chche -t chuyuxuan/se-350 .
        - docker push chuyuxuan/se-350:latest
      when:
       branch:
        - master

volumes:
  - name: cache
    host:
      path: /var/tmp/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
